# see https://pyup.io/docs/configuration/ for all available options

schedule: "every two weeks on tuesday"

# Security updates only - not just any newer version
update: insecure

search: False
requirements:
  - requirements-app.txt:
    update: insecure
  - requirements-dev.txt:
    update: insecure
  - requirements.txt:
      update: False
